# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308284608db998c8b0509819a889efb9877d9cd725d49cf7610b27b26e8aed392faf25c174baafe460cee701c7f24b2a7770fbc93c6c31555bdd035085406734

test:
  secret_key_base: 4cb6123b8917f6603b2e684514041e77c5bf80b117ccd0021a281328fc2344a4148f1d9300c610a76a869738eb227aa85d011786d39127bc56cc026e12f31de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
